import {useEffect,useMemo,useState} from 'react'
import {HarborMap} from './HarborMap'
import type {HarborState,LinkMode,PortCall} from './types'
import './styles.css'

const fmtTime=(v:string)=>new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v))
const usd=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v)
function Metric({label,value}:{label:string,value:string|number}){return <div className="metric-card"><span>{label}</span><strong>{value}</strong></div>}
function RiskPill({risk}:{risk:string}){return <span className={'risk '+risk}>{risk.toUpperCase()}</span>}
function PortCallCard({call,state}:{call:PortCall,state:HarborState}){const vessel=state.vessels.find(v=>v.id===call.vessel_id),berth=state.berths.find(b=>b.id===call.berth_id);return <div className="call-card"><div className="call-head"><div><strong>{vessel?.name}</strong><span>{vessel?.vessel_type} · {berth?.name}</span></div><RiskPill risk={call.risk}/></div><div className="call-stats"><span>ETA <b>{fmtTime(call.arrival_eta)}</b></span><span>Delay <b>{call.delay_minutes}m</b></span><span>Exposure <b>{usd(call.estimated_cost_exposure_usd)}</b></span></div><div className="stage-strip">{call.stages.map((s,i)=><div className="stage" key={s.code}><i className={i<3?'done':''}/><span>{s.label}</span></div>)}</div></div>}

export default function App(){
 const [state,setState]=useState<HarborState|null>(null),[online,setOnline]=useState(false)
 useEffect(()=>{let ws:WebSocket|undefined,dead=false;const connect=()=>{const protocol=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${protocol}://${location.host}/ws/harbor`);ws.onopen=()=>setOnline(true);ws.onmessage=e=>setState(JSON.parse(e.data));ws.onclose=()=>{setOnline(false);if(!dead)setTimeout(connect,1500)}};fetch('/api/v1/harbor').then(r=>r.json()).then(setState).catch(()=>{});connect();return()=>{dead=true;ws?.close()}},[])
 const exposure=useMemo(()=>state?.port_calls.reduce((s,p)=>s+p.estimated_cost_exposure_usd,0)??0,[state])
 async function setMode(mode:LinkMode){await fetch('/api/v1/connectivity',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode})})}
 if(!state)return <div className="boot">PORTFLOW<br/><span>Loading operations picture...</span></div>
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandmark">PF</div><div><b>PORTFLOW</b><span>OPERATIONS</span></div></div><nav><a className="active">Harbor Overview</a><a>Port Calls</a><a>Berth Board</a><a>Vessels</a><a>Services</a><a>Weather & Tide</a><a>Documents</a><a>Incidents</a></nav><div className="side-foot"><span className={online?'live-dot':''}/> {online?'LIVE STREAM':'RECONNECTING'}<small>Synthetic demo operations</small></div></aside>
 <main><header><div><p className="eyebrow">PORT OPERATIONS CONTROL TOWER</p><h1>{state.port_name}</h1></div><div className="header-right"><span>{new Date(state.generated_at).toLocaleString()}</span><button>Shift brief</button></div></header>
 <section className="metrics"><Metric label="VESSELS IN PICTURE" value={state.metrics.vessels_in_port_picture}/><Metric label="BERTHS OCCUPIED" value={`${state.metrics.berths_occupied}/${state.metrics.berths_total}`}/><Metric label="PORT CALLS AT RISK" value={state.metrics.port_calls_at_risk}/><Metric label="AVG DELAY" value={`${state.metrics.average_delay_minutes} min`}/><Metric label="MODELED EXPOSURE" value={usd(exposure)}/></section>
 <section className="grid"><div className="panel map-panel"><div className="panel-title"><div><span>LIVE HARBOR</span><b>Operational picture</b></div><small>Vessels · berths · movement</small></div><HarborMap state={state}/><div className="map-overlay"><div><span>WIND</span><b>{state.weather.wind_knots} kt</b></div><div><span>GUST</span><b>{state.weather.gust_knots} kt</b></div><div><span>WAVE</span><b>{state.weather.wave_height_m} m</b></div><div><span>TIDE</span><b>{state.weather.tide_m} m</b></div></div></div>
 <div className="panel right-stack"><div className="panel-title"><div><span>BERTH BOARD</span><b>Current allocation</b></div></div><div className="berths">{state.berths.map(b=><div className="berth-row" key={b.id}><div><b>{b.name}</b><span>{b.terminal}</span></div><span className={'berth-state '+b.status}>{b.status}</span></div>)}</div><div className="divider"/><div className="panel-title compact"><div><span>LINK STATE</span><b>{state.connectivity.primary_link}</b></div><RiskPill risk={state.connectivity.mode==='full'?'low':state.connectivity.mode==='offline_edge'?'critical':'high'}/></div><div className="link-meta"><span>{state.connectivity.bandwidth_kbps.toLocaleString()} kbps</span><span>{state.connectivity.queued_events} queued</span></div><div className="mode-buttons">{(['full','degraded','critical','offline_edge'] as LinkMode[]).map(m=><button className={state.connectivity.mode===m?'selected':''} onClick={()=>setMode(m)} key={m}>{m.replace('_',' ')}</button>)}</div></div></section>
 <section className="lower"><div className="panel"><div className="panel-title"><div><span>PORT CALLS</span><b>Critical path and cost exposure</b></div><small>dependency-aware</small></div><div className="calls">{state.port_calls.map(c=><PortCallCard call={c} state={state} key={c.id}/>)}</div></div><div className="panel"><div className="panel-title"><div><span>OPERATIONS FEED</span><b>Events and exceptions</b></div></div><div className="event-feed">{state.events.slice(0,8).map(e=><div className="event" key={e.id}><i className={e.severity}/><div><b>{e.title}</b><span>{e.message}</span></div><time>{fmtTime(e.occurred_at)}</time></div>)}</div></div></section><footer>{state.data_disclaimer}</footer></main></div>
}
