import { expect, test } from '@playwright/test'

const password = 'test-only customer passphrase 42'
test('customer onboarding, durable record editing, evidence and logout', async ({page}) => {
  await page.goto('/#setup=test-only-bootstrap-for-local-product-browser-suite')
  await expect(page.getByRole('heading', {name: 'Open your operational workspace'})).toBeVisible()
  await expect(page.getByLabel('Setup token')).toHaveCount(0)
  await expect(page).toHaveURL(/\/$/)
  await page.getByLabel('Full name').fill('Port Owner')
  await page.getByLabel('Email', {exact: true}).fill('owner@example.test')
  await page.getByLabel('Password', {exact: true}).fill(password)
  await page.getByRole('button', {name: 'Create workspace'}).click()
  await expect(page.getByRole('heading', {name: 'Your port. Your operational record.'})).toBeVisible()
  await expect(page.getByRole('region', {name:'Port operations command center'})).toBeVisible()
  await expect(page.getByRole('searchbox', {name:'Global workspace search'})).toBeVisible()
  await expect(page.getByRole('region',{name:'Port operations command center'}).getByRole('heading',{name:'Arrival runway',exact:true})).toBeVisible()
  await expect(page.getByRole('region', {name:'Operational geographic harbor map'})).toBeVisible()
  await expect(page.getByRole('heading', {name: 'Bring your first call into view'})).toBeVisible()
  await expect(page.locator('.product-boundary')).toContainText('Real operational mode.')
  await expect(page.locator('.product-boundary')).not.toContainText('Simulated operational picture.')
  await page.getByRole('link', {name:'Coordination', exact:true}).click()
  const emptyMap = page.getByRole('region', {name:'Operational geographic harbor map'})
  await expect(emptyMap).toBeVisible()
  await expect(emptyMap.getByText('Port geography is not configured.', {exact:true})).toBeVisible()
  await expect(emptyMap.locator('.maplibregl-canvas')).toBeVisible()
  await emptyMap.getByRole('button', {name:'Set up port geography', exact:true}).click()
  await expect(page.getByLabel(/^Latitude/)).toBeVisible()
  await expect(page.getByLabel(/^Longitude/)).toBeVisible()
  await page.getByRole('button', {name:'Cancel', exact:true}).click()
  await page.getByRole('link', {name:'Pulse', exact:true}).click()
  await page.getByRole('button', {name:'Set up port',exact:true}).click()
  await expect(page.getByLabel('Timezone')).toBeVisible()
  await page.getByRole('button', {name:'Cancel',exact:true}).click()
  await expect(page.getByRole('link', {name:'Calls', exact:true})).toBeVisible()
  await expect(page.getByRole('link', {name:'Exceptions', exact:true})).toBeVisible()
  await expect(page.getByRole('link', {name:'Recovery', exact:true})).toBeVisible()
  await page.getByRole('link', {name: 'Records', exact: true}).click()
  await page.getByRole('button', {name: 'Add record'}).click()
  await page.getByLabel('Name', {exact: true}).fill('Karachi Customer Port')
  await page.getByLabel('Timezone').fill('Asia/Karachi')
  await page.getByRole('button', {name: 'Save record'}).click()
  await expect(page.getByRole('heading', {name: 'Karachi Customer Port'})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', {name: 'Karachi Customer Port'})).toBeVisible()
  await page.getByRole('button', {name: 'Edit Karachi Customer Port'}).click()
  await page.getByLabel('Name', {exact: true}).fill('Karachi North Port')
  await page.getByRole('button', {name: 'Save record'}).click()
  await page.getByRole('link', {name: 'Evidence', exact: true}).click()
  await expect(page.getByText('Record history', {exact: true})).toBeVisible()
  await expect(page.locator('.product-history strong').filter({hasText:/^Karachi Customer Port$/})).toHaveCount(1)
  await expect(page.locator('.product-history strong').filter({hasText:/^Karachi North Port$/})).toHaveCount(1)
  await page.getByRole('button', {name: 'Sign out'}).click()
  await expect(page.getByRole('heading', {name: 'Sign in to Shorefront'})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', {name: 'Sign in to Shorefront'})).toBeVisible()
  expect(await page.evaluate(() => Object.keys(localStorage).filter(k => /token|password|session/i.test(k)))).toEqual([])
})

test('operational UI retains coastal dark mode and fits mobile', async ({page}) => {
  await page.setViewportSize({width: 375, height: 812})
  await page.goto('/')
  await page.getByLabel('Email', {exact: true}).fill('owner@example.test')
  await page.getByLabel('Password', {exact: true}).fill(password)
  await page.getByRole('button', {name: 'Sign in', exact: true}).click()
  await expect(page.getByRole('link', {name: 'Records', exact: true})).toBeVisible()
  await page.getByRole('button', {name: 'Switch to dark mode'}).click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('heading', {name: 'Your port. Your operational record.'})).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path: 'test-results/product-mobile-dark.png', fullPage: true})
  await page.setViewportSize({width: 1440, height: 1000})
  await page.getByRole('button', {name: 'Switch to light mode'}).click()
  await expect.poll(() => page.locator('.product-shell button').first().evaluate(el => getComputedStyle(el).color)).toBe('rgb(25, 47, 50)')
  await page.screenshot({path: 'test-results/product-desktop-light.png', fullPage: true})
})

test('real invitation, call setup, decision review and supervisor approval', async ({page, browser}) => {
  await page.goto('/')
  await page.getByLabel('Email', {exact:true}).fill('owner@example.test')
  await page.getByLabel('Password', {exact:true}).fill(password)
  await page.getByRole('button', {name:'Sign in', exact:true}).click()
  await expect(page.getByRole('link', {name:'Records', exact:true})).toBeVisible()
  const me = await (await page.request.get('/api/v1/auth/me')).json()
  const origin = 'http://127.0.0.1:5176'
  const headers = {Origin:origin, 'X-CSRF-Token':me.csrf_token}
  const records = await (await page.request.get('/api/v1/workspace')).json()
  const port = records.records.find((r:{kind:string}) => r.kind === 'port')
  for (const [kind,id,payload] of [
    ['berth','browser-berth',{name:'North Quay',port_id:port.record_id,max_length_m:300}],
    ['vessel','browser-vessel',{name:'Customer Meridian',length_m:220}],
    ['call','browser-call',{vessel_id:'browser-vessel',berth_id:'browser-berth',eta:'2026-10-03T10:00:00Z',etd:'2026-10-03T15:00:00Z'}],
  ] as const) {
    const result = await page.request.post(`/api/v1/records/${kind}`, {headers:{...headers,'Idempotency-Key':`browser-${id}`},data:{record_id:id,expected_revision:0,source:'Customer schedule',payload}})
    expect(result.status()).toBe(201)
  }
  await page.reload()
  await page.getByRole('link', {name:'Calls',exact:true}).click()
  await expect(page.locator('[data-product-workspace="calls"]')).toContainText('Customer Meridian')
  await expect(page.locator('[data-product-workspace="calls"]')).toContainText('North Quay')
  await expect(page.getByRole('table',{name:'Port call register'})).toBeVisible()
  await page.getByRole('button',{name:/Open call Customer Meridian/}).click()
  await expect(page.getByRole('region',{name:'Call command drawer'})).toContainText('Customer Meridian')
  await page.getByRole('link', {name:'Plan',exact:true}).click()
  await expect(page.locator('[data-product-workspace="plan"]')).toContainText('Customer Meridian')
  await page.getByLabel('Planned call').selectOption('browser-call')
  await page.getByRole('button', {name:'Prepare decision packet'}).click()
  await expect(page.getByRole('button', {name:'Approve recorded plan'})).toBeDisabled()
  await expect(page.getByText('Confidence: uncalibrated')).toBeVisible()
  await page.getByRole('link', {name:'Team',exact:true}).click()
  await page.getByLabel('Invitation email').fill('supervisor@example.test')
  await page.getByLabel('Role',{exact:true}).selectOption('supervisor')
  await page.getByRole('button',{name:'Create invitation'}).click()
  const token = await page.locator('.product-boundary code').innerText()
  const otherContext = await browser.newContext()
  const other = await otherContext.newPage()
  await other.goto(origin)
  await other.getByRole('button',{name:'I have an invitation'}).click()
  await other.getByLabel('Invitation token').fill(token)
  await other.getByLabel('Full name').fill('Duty Supervisor')
  await other.getByLabel('Email',{exact:true}).fill('supervisor@example.test')
  await other.getByLabel('Password',{exact:true}).fill(password)
  await other.getByRole('button',{name:'Accept invitation'}).click()
  await other.getByRole('link',{name:'Plan',exact:true}).click()
  await other.getByRole('button',{name:'Review packet'}).click()
  await other.getByLabel('Option to approve').selectOption('option-0')
  await other.getByLabel('Approval reason').fill('Reviewed against the customer berth plan; navigational checks remain external')
  await other.getByRole('button',{name:'Approve recorded plan'}).click()
  await expect(other.getByRole('heading',{name:'Approval recorded'})).toBeVisible()
  await other.getByLabel('Actual arrival (your local time)').fill('2026-10-03T10:20')
  await other.getByLabel('Actual departure (your local time)').fill('2026-10-03T15:30')
  await other.getByLabel('Observation source',{exact:true}).fill('Customer terminal log')
  await other.getByRole('button',{name:'Record observed outcome'}).click()
  await expect(other.getByText('Arrival deviation: 20 minutes')).toBeVisible()
  await expect(other.getByText('Occupancy deviation: 10 minutes')).toBeVisible()
  await other.reload()
  await other.getByRole('button',{name:'Review packet'}).click()
  await expect(other.getByText('Customer terminal log',{exact:true})).toBeVisible()
  await otherContext.close()
})


test('admin manages scoped data sources and partner projection credentials', async ({page}) => {
  const runtime=await (await page.request.get('/api/v1/runtime/capabilities')).json()
  await page.goto(runtime.needs_setup ? '/#setup=test-only-bootstrap-for-local-product-browser-suite' : '/')
  if(runtime.needs_setup) await page.getByLabel('Full name').fill('Port Owner')
  await page.getByLabel('Email', {exact:true}).fill('owner@example.test')
  await page.getByLabel('Password', {exact:true}).fill(password)
  await page.getByRole('button', {name:runtime.needs_setup?'Create workspace':'Sign in', exact:true}).click()
  await expect(page.getByRole('link', {name:'Connections', exact:true})).toBeVisible()
  await page.getByRole('link', {name:'Connections', exact:true}).click()
  await expect(page.getByRole('heading', {name:'Connect the port without surrendering the workspace.'})).toBeVisible()
  await expect(page.getByRole('heading', {name:'Validated external event contracts'})).toBeVisible()
  await expect(page.getByText('DCSA Port Call 2.0.0', {exact:true})).toBeVisible()

  await page.getByRole('button', {name:'Add data source', exact:true}).click()
  await page.getByLabel('Source ID').fill('browser-source')
  await page.getByLabel('Display name').fill('Browser source')
  await page.locator('.connection-standard-selector label').filter({hasText:'DCSA Port Call 2.0.0'}).getByRole('checkbox').check()
  await page.getByRole('button', {name:'Create source credential', exact:true}).click()
  const sourceReceipt=page.locator('.connection-token').filter({hasText:'Browser source'})
  await expect(sourceReceipt).toContainText('ONE-TIME CREDENTIAL')
  const sourceToken=(await sourceReceipt.locator('code').textContent())?.trim() ?? ''
  expect(sourceToken.length).toBeGreaterThanOrEqual(32)
  await sourceReceipt.getByRole('button',{name:'Hide credential'}).click()
  const sourceTable=page.getByRole('table',{name:'Data source registry'})
  await expect(sourceTable).toContainText('Browser source')
  await expect(sourceTable).toContainText('dcsa-port-call-2.0.0')
  await expect(sourceTable).not.toContainText(sourceToken)

  await page.getByRole('button', {name:'Create partner projection', exact:true}).click()
  await page.getByLabel('Grant ID').fill('browser-projection')
  await page.getByLabel('Partner / purpose').fill('Browser partner')
  await page.getByRole('button', {name:'Create projection credential', exact:true}).click()
  const grantReceipt=page.locator('.connection-token').filter({hasText:'Browser partner'})
  await expect(grantReceipt).toContainText('ONE-TIME CREDENTIAL')
  const grantToken=(await grantReceipt.locator('code').textContent())?.trim() ?? ''
  expect(grantToken.length).toBeGreaterThanOrEqual(32)
  await grantReceipt.getByRole('button',{name:'Hide credential'}).click()
  const grantTable=page.getByRole('table',{name:'Partner projection registry'})
  await expect(grantTable).toContainText('Browser partner')
  await expect(grantTable).not.toContainText(grantToken)

  const sourceRow=sourceTable.getByRole('row').filter({hasText:'Browser source'})
  await sourceRow.getByRole('button',{name:'Rotate'}).click()
  await expect(page.locator('.connection-token').filter({hasText:'Browser source'})).toBeVisible()
  await page.locator('.connection-token').filter({hasText:'Browser source'}).getByRole('button',{name:'Hide credential'}).click()
  await sourceRow.getByRole('button',{name:'Revoke'}).click()
  await expect(sourceRow).toContainText('REVOKED')
})

test('failed network logout does not silently reopen private data', async ({page}) => {
  await page.clock.install()
  await page.goto('/')
  await page.getByLabel('Email',{exact:true}).fill('owner@example.test')
  await page.getByLabel('Password',{exact:true}).fill(password)
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Your port. Your operational record.'})).toBeVisible()
  await page.route('**/api/v1/auth/logout', route => route.abort())
  await page.getByRole('button',{name:'Sign out'}).click()
  await expect(page.getByRole('heading',{name:'Sign in to Shorefront'})).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Server sign-out could not be confirmed')
  await page.clock.runFor(16000)
  await expect(page.getByRole('heading',{name:'Sign in to Shorefront'})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading',{name:'Sign in to Shorefront'})).toBeVisible()
})

test('validated file import and password change work in the browser', async ({page}) => {
  await page.goto('/')
  await page.getByLabel('Email',{exact:true}).fill('owner@example.test')
  await page.getByLabel('Password',{exact:true}).fill(password)
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await page.getByRole('link',{name:'Records',exact:true}).click()
  await page.getByRole('button',{name:'Import records'}).click()
  await page.getByLabel('Record file').setInputFiles({name:'customer-records.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({records:[{kind:'vessel',command:{record_id:'file-vessel',expected_revision:0,source:'Customer vessel register',payload:{name:'Imported Customer Vessel',length_m:210}}}]}))})
  await page.getByRole('button',{name:'Validate and import'}).click()
  await expect(page.getByText('Imported 1 record atomically.')).toBeVisible()
  await page.getByLabel('Record category').selectOption('vessel')
  await expect(page.getByRole('heading',{name:'Imported Customer Vessel'})).toBeVisible()
  await page.getByRole('link',{name:'Team',exact:true}).click()
  await page.getByLabel('Current password',{exact:true}).fill(password)
  await page.getByLabel('New password',{exact:true}).fill('new browser-only passphrase 456')
  await page.getByRole('button',{name:'Change password'}).click()
  await expect(page.getByText('Password changed. Other sessions have been revoked.')).toBeVisible()
})

test('invalid imports preserve data and open record forms disable writes offline', async ({page, context}) => {
  await page.goto('/')
  await page.getByLabel('Email',{exact:true}).fill('owner@example.test')
  await page.getByLabel('Password',{exact:true}).fill('new browser-only passphrase 456')
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await page.getByRole('link',{name:'Records',exact:true}).click()
  await page.getByRole('button',{name:'Import records'}).click()
  await page.getByLabel('Record file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{not json')})
  await page.getByRole('button',{name:'Validate and import'}).click()
  await expect(page.getByRole('alert')).toContainText('not valid JSON')
  await expect(page.getByRole('heading',{name:'Karachi North Port'})).toBeVisible()
  await page.getByRole('button',{name:'Close import'}).click()
  await page.getByRole('button',{name:'Add record'}).click()
  await page.getByLabel('Name',{exact:true}).fill('Unsubmitted port')
  await context.setOffline(true)
  await expect(page.getByRole('button',{name:'Save record'})).toBeDisabled()
  await expect(page.getByLabel('Name',{exact:true})).toHaveValue('Unsubmitted port')
  await context.setOffline(false)
  await page.getByRole('button',{name:'Retry connection'}).click()
  await expect(page.getByRole('button',{name:'Save record'})).toBeEnabled()
})

test('incident to assigned task to completion persists with its evidence', async ({page}) => {
  await page.goto('/')
  await page.getByLabel('Email',{exact:true}).fill('owner@example.test')
  await page.getByLabel('Password',{exact:true}).fill('new browser-only passphrase 456')
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await page.getByRole('link',{name:'Records',exact:true}).click()
  await page.getByLabel('Record category').selectOption('incident')
  await page.getByRole('button',{name:'Add record'}).click()
  await page.getByLabel('Title',{exact:true}).fill('Gangway inspection required')
  await page.getByRole('button',{name:'Save record'}).click()
  await expect(page.getByRole('heading',{name:'Gangway inspection required'})).toBeVisible()
  await page.getByLabel('Record category').selectOption('task')
  await page.getByRole('button',{name:'Add record'}).click()
  await page.getByLabel('Title',{exact:true}).fill('Inspect the north gangway')
  await page.getByLabel('Assigned to').selectOption({label:'Port Owner'})
  await page.getByLabel(/^Incident/).selectOption({label:'Gangway inspection required'})
  await page.getByLabel('Due (your local time)').fill('2026-10-04T16:00')
  await page.getByRole('button',{name:'Save record'}).click()
  await page.getByRole('link',{name:'Pulse',exact:true}).click()
  const action = page.locator('.ops-queue-item').filter({has:page.getByRole('heading',{name:'Inspect the north gangway'})})
  await expect(action).toContainText('Assigned to Port Owner')
  await page.getByRole('link',{name:'Records',exact:true}).click()
  await page.getByLabel('Record category').selectOption('task')
  await page.getByRole('button',{name:'Edit Inspect the north gangway'}).click()
  await page.getByRole('region',{name:'Record editor'}).getByLabel('Status').selectOption('done')
  await page.getByLabel('Completion note').fill('Inspection recorded in terminal safety log SF-42')
  await page.getByRole('button',{name:'Save record'}).click()
  await page.reload()
  await page.getByRole('link',{name:'Pulse',exact:true}).click()
  await expect(page.getByText('Inspect the north gangway',{exact:true})).toHaveCount(0)
  await expect(page.getByRole('heading',{name:'Gangway inspection required',exact:true})).toBeVisible()
  await page.getByRole('link',{name:'Evidence',exact:true}).click()
  await expect(page.locator('.product-history strong').filter({hasText:/^Inspect the north gangway$/})).toHaveCount(2)
})

test('late password rotation response cannot reopen a signed-out workspace', async ({page}) => {
  await page.goto('/')
  await page.getByLabel('Email',{exact:true}).fill('owner@example.test')
  await page.getByLabel('Password',{exact:true}).fill('new browser-only passphrase 456')
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await page.getByRole('link',{name:'Team',exact:true}).click()
  let release!:()=>void
  let reached!:()=>void
  const held = new Promise<void>(resolve => {release=resolve})
  const committed = new Promise<void>(resolve => {reached=resolve})
  await page.route('**/api/v1/auth/password', async route => {
    const response = await route.fetch()
    expect(response.status()).toBe(200)
    reached()
    await held
    await route.fulfill({response})
  })
  await page.getByLabel('Current password',{exact:true}).fill('new browser-only passphrase 456')
  await page.getByLabel('New password',{exact:true}).fill('rotated browser-only passphrase 789')
  await page.getByRole('button',{name:'Change password'}).click()
  await committed
  await page.getByRole('button',{name:'Sign out'}).click()
  await expect(page.getByRole('heading',{name:'Sign in to Shorefront'})).toBeVisible()
  const completed = page.waitForResponse('**/api/v1/auth/password')
  release()
  await completed
  await page.getByRole('link',{name:/SHOREFRONT/}).focus()
  await expect(page.getByRole('heading',{name:'Sign in to Shorefront'})).toBeVisible()
  await expect(page.getByRole('navigation',{name:'Workspace'})).toHaveCount(0)
})
