import {expect,test} from '@playwright/test'

test('Quay berth planning board opens full screen with exit and shows recorded call blocks',async({page},testInfo)=>{
  await page.setViewportSize({width:1440,height:900})
  await page.goto('/?showcase=1#plan')
  const quay=page.getByRole('region',{name:'Quay berth planning board'})
  await expect(quay).toBeVisible()
  await expect(quay.getByText('North Quay')).toBeVisible()
  await quay.getByRole('button',{name:'Full screen quay'}).click()
  await expect(quay).toHaveAttribute('data-quay-expanded','true')
  const bounds=await quay.boundingBox()
  expect(bounds!.width).toBeGreaterThan(1435)
  expect(bounds!.height).toBeGreaterThan(895)
  await expect(quay.getByRole('button',{name:'Exit full screen quay'})).toBeVisible()
  await expect(quay.getByText('MV Aurora')).toBeVisible()
  await page.screenshot({path:testInfo.outputPath('quay-plan-desktop.png')})
  await page.keyboard.press('Escape')
  await expect(quay).toHaveAttribute('data-quay-expanded','false')
})

test('Quay operating horizon expands independently of map and preserves timeframe',async({page})=>{
  await page.goto('/?showcase=1#pulse')
  const quay=page.getByRole('region',{name:'Port operating horizon'})
  await expect(quay).toBeVisible()
  await quay.getByRole('button',{name:'12H'}).click()
  await quay.getByRole('button',{name:'Full screen quay'}).click()
  await expect(quay).toHaveAttribute('data-quay-expanded','true')
  await expect(quay.getByRole('button',{name:'12H'})).toHaveAttribute('aria-pressed','true')
  await expect(quay.getByText('North Quay')).toBeVisible()
  await quay.getByRole('button',{name:'Exit full screen quay'}).click()
  await expect(quay).toHaveAttribute('data-quay-expanded','false')
  await expect(quay.getByRole('button',{name:'12H'})).toHaveAttribute('aria-pressed','true')
})

test('Quay fullscreen on mobile works without native fullscreen in dark mode',async({page},testInfo)=>{
  await page.addInitScript(()=>{Object.defineProperty(Element.prototype,'requestFullscreen',{configurable:true,value:undefined})})
  await page.setViewportSize({width:390,height:844})
  await page.goto('/?showcase=1#plan')
  await page.getByRole('button',{name:'Dark mode',exact:true}).click()
  const quay=page.getByRole('region',{name:'Quay berth planning board'})
  await quay.getByRole('button',{name:'Full screen quay'}).click()
  await expect(quay).toHaveAttribute('data-quay-expanded','true')
  const bounds=await quay.boundingBox()
  expect(bounds!.width).toBeGreaterThanOrEqual(388)
  expect(bounds!.height).toBeGreaterThanOrEqual(840)
  await expect(quay.getByText('North Quay')).toBeVisible()
  await expect(quay.getByRole('button',{name:'Exit full screen quay'})).toBeInViewport()
  await page.screenshot({path:testInfo.outputPath('quay-plan-mobile-dark.png')})
  await page.keyboard.press('Escape')
  await expect(quay).toHaveAttribute('data-quay-expanded','false')
  expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden')
})
