import {expect, test} from '@playwright/test'
import {workflowSession, workflowCall, workflowPassword, writeFact} from './workflow-fixture'

test('call workspace creates linked incidents and tasks with actionable exception closeout', async ({page}) => {
  await workflowSession(page)
  await workflowCall(page,'context')
  await page.getByRole('link',{name:'Calls',exact:true}).click()
  const call = page.getByRole('article').filter({has:page.getByRole('heading',{name:'context vessel',exact:true})})
  await call.getByRole('button',{name:'Record incident',exact:true}).click()
  await page.getByLabel('Title',{exact:true}).fill('Contextual gangway fault')
  await expect(page.getByLabel(/^Port call/)).toHaveValue('context-call')
  await page.getByRole('button',{name:'Save record',exact:true}).click()
  await expect(call.getByText('Contextual gangway fault',{exact:true})).toBeVisible()
  await page.getByRole('link',{name:'Exceptions',exact:true}).click()
  const incident = page.locator('.ops-queue-item').filter({has:page.getByRole('heading',{name:'Contextual gangway fault',exact:true})})
  await incident.getByRole('button',{name:'Assign task',exact:true}).click()
  await page.getByLabel('Title',{exact:true}).fill('Repair contextual gangway')
  await expect(page.getByLabel(/^Port call/)).toHaveValue('context-call')
  await expect(page.getByLabel(/^Incident/).locator('option:checked')).toHaveText('Contextual gangway fault')
  await page.getByLabel(/^Assigned to/).selectOption({index:1})
  await page.getByLabel('Due (your local time)').fill('2026-10-03T12:00')
  await page.getByRole('button',{name:'Save record',exact:true}).click()
  const task = page.getByRole('article').filter({hasText:'Repair contextual gangway'})
  await task.getByRole('button',{name:'Update record',exact:true}).click()
  const editor = page.getByRole('region',{name:'Record editor'})
  await editor.locator('select[name="status"]').selectOption('done')
  await editor.locator('input[name="completion_note"]').fill('Repair accepted in terminal log GH-17')
  await editor.getByRole('button',{name:'Save record',exact:true}).click()
  await expect(task).toHaveCount(0)
  await page.reload()
  const facts = (await (await page.request.get('/api/v1/workspace')).json()).records
  const saved = facts.find((r:{payload:{title:string}})=>r.payload.title==='Repair contextual gangway')
  expect(saved.payload).toMatchObject({call_id:'context-call',status:'done',completion_note:'Repair accepted in terminal log GH-17'})
  expect(saved.payload.incident_id).toBeTruthy()
})

test('named recipient coordinates handoff and commitment preserving exact terms', async ({page,browser}) => {
  const owner = await workflowSession(page)
  await workflowCall(page,'coord')
  const invitation = await page.request.post('/api/v1/auth/invitations',{
    headers:{Origin:'http://127.0.0.1:5176','X-CSRF-Token':owner.csrf_token},data:{email:'coord-recipient@example.test',role:'operator'},
  })
  expect(invitation.status()).toBe(201)
  const recipientContext = await browser.newContext()
  const recipient = await recipientContext.newPage()
  const accept = await recipient.request.post('http://127.0.0.1:5176/api/v1/auth/accept',{
    headers:{Origin:'http://127.0.0.1:5176'},data:{email:'coord-recipient@example.test',display_name:'Duty Recipient',password:workflowPassword,invitation_token:(await invitation.json()).invitation_token},
  })
  expect(accept.status()).toBe(201)
  const member = await accept.json()
  const terms = {call_id:'coord-call',recipient_id:member.user.id,due_at:'2026-10-05T14:00:37.123456+05:00',note:'Document bundle manifest H-17'}
  await writeFact(page,'handoff','coord-handoff',{...terms,title:'Shift transfer',status:'prepared'})
  await writeFact(page,'commitment','coord-commitment',{...terms,title:'Pilot readiness',status:'proposed'})
  await page.getByRole('link',{name:'Coordination',exact:true}).click()
  const handoff = page.getByRole('article').filter({has:page.getByRole('heading',{name:'Shift transfer',exact:true})})
  await expect(handoff.getByRole('button',{name:'Acknowledge handoff',exact:true})).toHaveCount(0)
  await handoff.getByRole('button',{name:'Send handoff',exact:true}).click()
  await page.getByLabel('Action source').fill('Shift desk log H-17')
  await page.getByRole('button',{name:'Confirm action',exact:true}).click()
  await expect(handoff).toContainText('sent')
  await recipient.goto('http://127.0.0.1:5176/#coordination')
  const received = recipient.getByRole('article').filter({has:recipient.getByRole('heading',{name:'Shift transfer',exact:true})})
  await received.getByRole('button',{name:'Acknowledge handoff',exact:true}).click()
  await recipient.getByLabel('Evidence / confirmation').fill('Received and checked manifest H-17 at the duty desk')
  await recipientContext.setOffline(true)
  await expect(recipient.getByRole('button',{name:'Confirm action',exact:true})).toBeDisabled()
  await expect(recipient.getByLabel('Evidence / confirmation')).toHaveValue('Received and checked manifest H-17 at the duty desk')
  await recipientContext.setOffline(false)
  await recipient.getByRole('button',{name:'Retry connection'}).click()
  await recipient.getByRole('button',{name:'Confirm action',exact:true}).click()
  await recipient.getByLabel('Coordination scope').selectOption('all')
  await expect(received).toContainText('acknowledged')
  await expect(received.getByRole('button',{name:'Acknowledge handoff',exact:true})).toHaveCount(0)
  const commitment = recipient.getByRole('article').filter({has:recipient.getByRole('heading',{name:'Pilot readiness',exact:true})})
  await commitment.getByRole('button',{name:'Accept commitment',exact:true}).click()
  await recipient.getByRole('button',{name:'Confirm action',exact:true}).click()
  await commitment.getByRole('button',{name:'Fulfill commitment',exact:true}).click()
  await recipient.getByLabel('Evidence / confirmation').fill('Pilot desk completion record PD-17')
  await recipient.getByRole('button',{name:'Confirm action',exact:true}).click()
  await expect(commitment).toContainText('fulfilled')
  const saved = (await (await recipient.request.get('http://127.0.0.1:5176/api/v1/workspace')).json()).records
  expect(saved.find((r:{record_id:string})=>r.record_id==='coord-handoff').payload).toMatchObject({...terms,status:'acknowledged'})
  expect(saved.find((r:{record_id:string})=>r.record_id==='coord-commitment').payload).toMatchObject({...terms,status:'fulfilled',proof:'Pilot desk completion record PD-17'})
  await recipientContext.close()
})
